// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDrH74o6FIMowxMiTx3Pw-H1VVfdC3u6Y',
    appId: '1:738196187589:web:a2612af72c4cbf2c5083ac',
    messagingSenderId: '738196187589',
    projectId: 'tobeto-2a-fe3fa',
    authDomain: 'tobeto-2a-fe3fa.firebaseapp.com',
    storageBucket: 'tobeto-2a-fe3fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTWIA_hB0x-ChLM0emi3vEcE9cGXH8XEY',
    appId: '1:738196187589:android:ac24f5342d21a2095083ac',
    messagingSenderId: '738196187589',
    projectId: 'tobeto-2a-fe3fa',
    storageBucket: 'tobeto-2a-fe3fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcxvu4T77EdwsdOYw_s_DWqz6wFouJUcM',
    appId: '1:738196187589:ios:96224dcb03a408975083ac',
    messagingSenderId: '738196187589',
    projectId: 'tobeto-2a-fe3fa',
    storageBucket: 'tobeto-2a-fe3fa.appspot.com',
    iosBundleId: 'com.example.firebaseIntro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcxvu4T77EdwsdOYw_s_DWqz6wFouJUcM',
    appId: '1:738196187589:ios:96224dcb03a408975083ac',
    messagingSenderId: '738196187589',
    projectId: 'tobeto-2a-fe3fa',
    storageBucket: 'tobeto-2a-fe3fa.appspot.com',
    iosBundleId: 'com.example.firebaseIntro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDrH74o6FIMowxMiTx3Pw-H1VVfdC3u6Y',
    appId: '1:738196187589:web:d8580e22310b3d605083ac',
    messagingSenderId: '738196187589',
    projectId: 'tobeto-2a-fe3fa',
    authDomain: 'tobeto-2a-fe3fa.firebaseapp.com',
    storageBucket: 'tobeto-2a-fe3fa.appspot.com',
  );
}
